stages:
- stage: amd64
  jobs:
  - template: debootstrap_architecture_template.yml
    parameters:
      arch: x86_64
      agent_arch: X64
      arch_dir: x64
      aws_instance_id: i-072a16dc951b04894
  - job: startAgent
    pool:
      vmImage: ubuntu-latest
    variables:
      AWS_INSTANCE_ID: ${{ parameters.aws_instance_id }}

    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure subscription 1(cab104b5-7437-4adb-8ce9-cc164ab9d78c)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az vm start -g CreateImages -n CreateImageRHEL'
      displayName: 'Start instance'

#- stage: arm64
#  dependsOn: []
#  jobs:
#    - template: debootstrap_architecture_template.yml
#      parameters:
#        arch: arm64
#        agent_arch: ARM64
#        arch_dir: ARM64
#        aws_instance_id: i-0abed7e4b7595271e
