[oobe]
command = /etc/oobe.sh
defaultUid = 1000
defaultName = PengwinEnterprise9

[shortcut]
enabled = true
icon = /usr/lib/wsl/pengwin-enterprise.theme-dark.ico

[windowsterminal]
enabled = true
ProfileTemplate = /usr/lib/wsl/terminal-profile.json
